import matplotlib.pyplot as plt
import seaborn as sns
import regex as re

Country = ['USA','Canada','Germany','UK','France']
GDP_Per_Capita = [45,42,52,49,47]

fig = plt.figure(0)
# fig.canvas.set_window_title('Window 3D')
# plt.figure(figsize=(20,10))
plt.scatter(Country, GDP_Per_Capita, marker='.', c='#32a83c')
plt.title('Country Vs GDP Per Capita')
plt.xlabel('Country')
plt.ylabel('GDP Per Capita')
plt.show()



# plt.pie([80,20], labels=['Likely','Not Likely'])
# plt.title('Likilihood')
# # plt.subplots(num="title")
# # # plt.figure(figsize=(20,10))
# # plt.xlabel('Country')
# # plt.ylabel('GDP Per Capita')

# # plt.ion()  # to make plot non-blocking, i.e. if multiple plots are launched
# plt.show()







# x = [
# 	'Kanye West', 'Drake', 'Tom Misch', 'Mac Miller', 'Kendrick Lamar',
# 	'Tame Impala', 'BROCKHAMPTON', 'Lana Del Rey', 'John Legend',
# 	'Anderson .Paak', 'Whitney', 'Frank Ocean' 'JAY-Z' 'Marc E. Bassy',
# 	'Vulfpeck', 'Oh Wonder', 'Lil Wayne', 'Leon Bridges', 'Still Woozy',
# 	'Post Malone', 'Tyler, The Creator', 'Magic City Hippies', 'UPSAHL', 'HONNE',
# 	'LEISURE', 'Big Sean', 'LÉON', 'ODESZA', 'flor', 'Daniel Caesar',
# 	'King Princess', 'Big Wild', 'Rick Ross', 'GRiZ', 'Pond', 'Maribou State',
# 	'A$AP Rocky', 'Jack Johnson', 'Amber Mark', 'Bruno Mars', 'Khalid',
# 	'Lianne La Havas', 'Skizzy Mars', 'The Head And The Heart', 'Alina Baraz',
# 	'Bazzi' 'Snakehips', 'Emily King', 'Men I Trust', 'Wale', 'G-Eazy',
# 	'Saint Motel', 'Calvin Harris', 'Chiddy Bang', 'Lost Kings', 'FKJ', 'Rihanna',
# 	'The Holydrug Couple', 'Phoebe Bridgers', 'STRFKR', 'Joey Bada$$',
# 	'Ark Patrol', 'Flume', 'Franc Moody', 'Harry Styles', 'Chance the Rapper',
# 	'Various Artists' 'John Mayer', 'JR JR', 'Jaymes Young', 'J. Cole',
# 	'Tim Atlas', 'Møme', 'Dominic Fike', 'Coldplay', 'ODIE', 'H.E.R.' 'Aminé',
# 	'Young the Giant', 'COIN', 'Noname', 'BabyJake', 'UMI', 'Houses', '20syl',
# 	'The Weeknd', 'Radiohead', 'Mt. Joy', 'BANKS', 'Phlake', 'Miguel', 'Pusha T',
# 	'KAYTRANADA', 'Ella Eyre', 'Future', 'Koi Child', 'Travis Scott', 'Tennis',
# 	'The Neighbourhood','Barrie', 'Prelow', 'Vacationer', 'The 1975', 'Adele',
# 	'Fleetwood Mac', 'Dave Matthews Band', 'Superorganism' 'Andy Shauf',
# 	'Sabrina Claudio', 'The Internet', 'Grizfolk', 'Quinn XCII',
# 	'Francis and the Lights', 'Blood Orange', 'The Beatles', 'Alabama Shakes',
# 	'Childish Gambino', 'Gus Dapperton', 'Mac DeMarco', '6LACK', 'Ari Lennox',
# 	'Jhené Aiko', 'Jessie Reyez', 'Skinshape', '2 Chainz', 'Augustine', 'SALES',
# 	'PREP', 'MAY-A', 'Foster The People', 'Yuno', 'Swim Mountain', 'Wet',
# 	'Wiz Khalifa', 'Cautious Clay', 'DJ Khaled', 'Sam Smith', 'Lorde', 'Eminem',
# 	'Medasin', 'Saba Abraha', 'Chiiild', 'NoMBe', 'Earth, Wind & Fire',
# 	'Petit Biscuit', 'Olivia Dean', 'Kacey Musgraves', 'Beirut',
# 	'Charlotte Day Wilson', 'Galantis', 'Moon Taxi', 'Elton John', 'Bon Iver',
# 	'SZA', 'Capital Cities', 'Julia Jacklin', 'Action Bronson',
# 	'Robby Hunter Band', 'Ariana Grande', 'Big Gigantic', 'Summer Salt',
# 	'Laura Misch', 'Rex Orange County', 'Bea Miller', 'Japanese Breakfast',
# 	'Maroon 5', 'Billie Eilish', 'ZOLA', 'OneRepublic',
# 	'Unknown Mortal Orchestra', 'Pretty Lights', 'May Erlewine', 'Beach House',
# 	'Shawn Mendes', 'MyKey', 'DRAM' 'Generationals' 'BØRNS' 'Quentin Miller',
# 	'Rhye', 'Dori Valentine', 'Astronomyy', 'S. Carey', 'The Brook & The Bluff',
# 	'Run The Jewels', 'Fleet Foxes', 'LANKS', 'Glass Animals', 'Brittany Howard',
# 	'Star Parks', 'French Montana', 'Mark Ronson', 'Keenan', 'Rae Sremmurd',
# 	'Kat Dahlia', 'Clairo', 'RŮDE', 'TOPS', 'Lou Doillon', 'Ruby Empress',
# 	'Penny and Sparrow', 'Twenty One Pilots', 'Saje', 'LEO ISLO', 'Gold Panda',
# 	'Raveena', 'Bennett Coast', 'Sylvan Esso', 'Duckwrth', 'NxWorries', 'Fryars',
# 	'Yoke Lore', 'Robert Glasper', 'WALK THE MOON', 'Ms. Lauryn Hill',
# 	'Jorja Smith', 'HOMESHAKE', 'SEBASTIAN PAUL', 'Odd Future', 'Spoon', 'Journey',
# 	'Yung Lean', 'A Tribe Called Quest', 'Mura Masa', 'The Temptations',
# 	'Electric Guest', 'Washed Out', 'Eagles', 'ASL', 'The Jackson 5',
# 	'Gardens & Villa', 'Passion Pit', 'Theophilus London', 'Nick Leng', 'Valley',
# 	'Monophonics', 'JAHKOY', 'Imagine Dragons', 'Bas', 'Ty Dolla $ign', 'Pell',
# 	'Isaac Dunbar', 'Jordana', 'Niall Horan', 'Macklemore', 'Sia', 'M. T. Hadley',
# 	'Gregory Porter', 'ELIO', 'Anna of the North', 'Kate Bollinger', 'Thundercat',
# 	'MIA GLADSTONE', 'Sam Gellaitry', 'Justin Timberlake', 'Paul McCartney',
# 	'Winnetka Bowling League', 'Joji', 'John K', '88-Keys', 'Kikagaku Moyo',
# 	'Curren$y', 'Dawn Golden', 'Maggie Rogers', 'Pharrell Williams' 'Zedd',
# 	'Bad Suns', 'Kyla La Grange', 'Blake Ruby', 'Red Hearse', 'Bahamas',
# 	'Aaron Frazer', 'DJ Shadow', 'Angus & Julia Stone', 'The Lumineers',
# 	'Carmody', 'ford.', 'Samia', 'Cool Company', 'Lord Huron', 'Nelly',
# 	'Hazel English', 'Miki Fiki', 'Louis The Child', 'Demi Lovato', 'Fruit Bats',
# 	'Mike Shinoda', 'Jess Best', 'Ricky Reed', 'Hozier', 'Fishing in Japan',
# 	'India Shawn', 'Hope Tala', 'Bibio', 'Jackson Lundy', 'Black Pumas',
# 	'Bishop Briggs', 'keshi', 'HNNY', 'Derek Simpson', '88rising', 'Hether',
# 	'Vansire', 'KASSEO', 'Paloma Faith', 'The Japanese House', 'Rook Monroe',
# 	'Wes Reeve', 'Matt Quentin', 'vbnd', 'Cape Francis', 'NGHTMRE', 'Healy',
# 	'Tommy Newport', 'Moi Je', 'FELIVAND', 'New West', 'Eleni Drake',
# 	'This Is The Kit', 'Devon Gilfillian', 'French For Rabbits', 'Tash Sultana',
# 	'Lil Nas X', 'C2C', 'Alë Jay', 'Tora', 'ayokay', 'K. Roosevelt', '¿Téo?',
# 	'Golden Vessel', 'Young Thug', 'BAYNK', 'Cheat Codes', 'Lexi Jayde', 'Wallows',
# 	'Tiana Major9', 'Tourist', 'Tōth', 'Honeywhip', 'Marvin Gaye', 'Szymon',
# 	'Busta Rhymes', 'Santana', 'Gregory Alan Isakov', 'Portugal. The Man',
# 	'Matoma', 'Avicii', 'Disclosure', 'Darius', 'Miles Davis', 'Yahtzel',
# 	'Mutemath', 'Kartell', 'Roy Woods', 'Tunji Ige', 'Manila Killa',
# 	'The Dramatics', 'Injury Reserve', 'YOSIE', 'Henry Green', 'Giraffage',
# 	'Beshken', 'Commodores', 'Seal', 'Raury', 'Major Lazer', 'Kygo', 'Night Moves',
# 	'Seinabo Sey', 'Isaiah Rashad', 'Knox Fortune', 'Toploader', 'Garren Sean',
# 	'BADBADNOTGOOD' 'Royal Tongues' 'XY&O' 'Foxygen' 'Jamie xx' 'CeeLo Green',
# 	'B.o.B', 'Masego', 'Jacob Collier', 'Whethan', 'Hayden James', 'Jordan Rakei',
# 	'MKTO', 'Jeremih', 'Floro', 'Marshmello', 'ZHU', 'Syd', 'Mr. Probz',
# 	'Mary J. Blige', 'Dreamville', 'Meek Mill', 'Dido', 'Estelle',
# 	'Louis Armstrong', 'Julie London', 'JID', 'Marian Hill', 'Ra Ra Riot',
# 	'A$AP Twelvyy', 'Earl Sweatshirt', 'tobi lou', 'Russ', 'VIC MENSA',
# 	'Snoop Dogg', 'Huncho Jack', 'Mild High Club', 'Brian Culbertson',
# 	'The Rolling Stones', 'Catching Flies', 'Appleby', 'Social House', 'GoldLink',
# 	'Aphex Twin', 'McClenney', 'Dream Koala', 'Hoodie Allen', 'Tiara Thomas',
# 	'Fyfe', 'Hippie Sabotage', 'Two Another', 'Clean Bandit', 'Craft Spells',
# 	'Verzache', 'Selena Gomez', 'The Marías', 'Choker', 'Lizzo', 'Steve Lacy',
# 	'Kasbo', 'Hablot Brown', 'DRAMA', 'Jarryd James', 'Gnarls Barkley', 'meija',
# 	'Girlyboi', 'Khruangbin', 'Peach Tree Rascals', 'Litany', 'THEY.',
# 	'Loyle Carner', 'Crumb', 'Elton Aura', 'Rizzle Kicks', 'Bonobo', 'Solange',
# 	'Two Feet', 'The Hails', 'Sjowgren', 'Galimatias', 'Kali Uchis',
# 	'Mick Jenkins', 'Phum Viphurit', 'Kelsy Karter', 'Jalen Santoy',
# 	'The Carters', 'Tove Styrke', 'The Notorious B.I.G.', 'Ralph Castelli',
# 	'Ruel', 'Sinéad Harnett', 'Summer Walker', 'Danrell x Småland', 'MGMT',
# 	'Daft Punk', 'Jason Mraz', 'Empire of the Sun', 'Local Natives', 'MELVV',
# 	'Sampha', 'Party Pupils', 'ScHoolboy Q', 'Bob Marley & The Wailers',
# 	'Grizzly Bear', 'Kool & The Gang', 'Sports', 'Hollow Coves']
x = [
'Kanye West',
'Drake',
'Tom Misch',
'Mac Miller',
'Kendrick Lamar',
'Tame Impala',
'BROCKHAMPTON',
'Lana Del Rey',
'John Legend',
'Anderson .Paak',
'Whitney',
'Frank Ocean',
'JAY-Z',
'Marc E. Bassy',
'Vulfpeck',
'Oh Wonder',
'Lil Wayne',
'Leon Bridges',
'Still Woozy',
'Post Malone',
'Tyler, The Creator',
'Magic City Hippies',
'UPSAHL',
'HONNE',
'LEISURE',
'Big Sean',
'LÉON',
'ODESZA',
'flor',
'Daniel Caesar',
'King Princess',
'Big Wild',
'Rick Ross',
'GRiZ',
'Pond',
'Maribou State',
'A$AP Rocky',
'Jack Johnson',
'Amber Mark',
'Bruno Mars',
'Khalid',
'Lianne La Havas',
'Skizzy Mars',
'The Head And The Heart',
'Alina Baraz',
'Bazzi',
'Snakehips',
'Emily King',
'Men I Trust',
'Wale',
'G-Eazy',
'Saint Motel',
'Calvin Harris',
'Chiddy Bang',
'Lost Kings',
'FKJ',
'Rihanna',
'The Holydrug Couple',
'Phoebe Bridgers',
'STRFKR',
'Joey Bada$$',
'Ark Patrol',
'Flume',
'Franc Moody',
'Harry Styles',
'Chance the Rapper',
'Various Artists',
'John Mayer',
'JR JR',
'Jaymes Young',
'J. Cole',
'Tim Atlas',
'Møme',
'Dominic Fike',
'Coldplay',
'ODIE',
'H.E.R.',
'Aminé',
'Young the Giant',
'COIN',
'Noname',
'BabyJake',
'UMI',
'Houses',
'20syl',
'The Weeknd',
'Radiohead',
'Mt. Joy',
'BANKS',
'Phlake',
'Miguel',
'Pusha T',
'KAYTRANADA',
'Ella Eyre',
'Future',
'Koi Child',
'Travis Scott',
'Tennis',
'The Neighbourhood',
'Barrie',
'Prelow',
'Vacationer',
'The 1975',
'Adele',
'Fleetwood Mac',
'Dave Matthews Band',
'Superorganism',
'Andy Shauf',
'Sabrina Claudio',
'The Internet',
'Grizfolk',
'Quinn XCII',
'Francis and the Lights',
'Blood Orange',
'The Beatles',
'Alabama Shakes',
'Childish Gambino',
'Gus Dapperton',
'Mac DeMarco',
'6LACK',
'Ari Lennox',
'Jhené Aiko',
'Jessie Reyez',
'Skinshape',
'2 Chainz',
'Augustine',
'SALES',
'PREP',
'MAY-A',
'Foster The People',
'Yuno',
'Swim Mountain',
'Wet',
'Wiz Khalifa',
'Cautious Clay',
'DJ Khaled',
'Sam Smith',
'Lorde',
'Eminem',
'Medasin',
'Saba Abraha',
'Chiiild',
'NoMBe',
'Earth, Wind & Fire',
'Petit Biscuit',
'Olivia Dean',
'Kacey Musgraves',
'Beirut',
'Charlotte Day Wilson',
'Galantis',
'Moon Taxi',
'Elton John',
'Bon Iver',
'SZA',
'Capital Cities',
'Julia Jacklin',
'Action Bronson',
'Robby Hunter Band',
'Ariana Grande',
'Big Gigantic',
'Summer Salt',
'Laura Misch',
'Rex Orange County',
'Bea Miller',
'Japanese Breakfast',
'Maroon 5',
'Billie Eilish',
'ZOLA',
'OneRepublic',
'Unknown Mortal Orchestra',
'Pretty Lights',
'May Erlewine',
'Beach House',
'Shawn Mendes',
'MyKey',
'DRAM',
'Generationals',
'BØRNS',
'Quentin Miller',
'Rhye',
'Dori Valentine',
'Astronomyy',
'S. Carey',
'The Brook & The Bluff',
'Run The Jewels',
'Fleet Foxes',
'LANKS',
'Glass Animals',
'Brittany Howard',
'Star Parks',
'French Montana',
'Mark Ronson',
'Keenan',
'Rae Sremmurd',
'Kat Dahlia',
'Clairo',
'RŮDE',
'TOPS',
'Lou Doillon',
'Ruby Empress',
'Penny and Sparrow',
'Twenty One Pilots',
'Saje',
'LEO ISLO',
'Gold Panda',
'Raveena',
'Bennett Coast',
'Sylvan Esso',
'Duckwrth',
'NxWorries',
'Fryars',
'Yoke Lore',
'Robert Glasper',
'WALK THE MOON',
'Ms. Lauryn Hill',
'Jorja Smith',
'HOMESHAKE',
'SEBASTIAN PAUL',
'Odd Future',
'Spoon',
'Journey',
'Yung Lean',
'A Tribe Called Quest',
'Mura Masa',
'The Temptations',
'Electric Guest',
'Washed Out',
'Eagles',
'ASL',
'The Jackson 5',
'Gardens & Villa',
'Passion Pit',
'Theophilus London',
'Nick Leng',
'Valley',
'Monophonics',
'JAHKOY',
'Imagine Dragons',
'Bas',
'Ty Dolla $ign',
'Pell',
'Isaac Dunbar',
'Jordana',
'Niall Horan',
'Macklemore',
'Sia',
'M. T. Hadley',
'Gregory Porter',
'ELIO',
'Anna of the North',
'Kate Bollinger',
'Thundercat',
'MIA GLADSTONE',
'Sam Gellaitry',
'Justin Timberlake',
'Paul McCartney',
'Winnetka Bowling League',
'Joji',
'John K',
'88-Keys',
'Kikagaku Moyo',
'Curren$y',
'Dawn Golden',
'Maggie Rogers',
'Pharrell Williams',
'Zedd',
'Bad Suns',
'Kyla La Grange',
'Blake Ruby',
'Red Hearse',
'Bahamas',
'Aaron Frazer',
'DJ Shadow',
'Angus & Julia Stone',
'The Lumineers',
'Carmody',
'ford.',
'Samia',
'Cool Company',
'Lord Huron',
'Nelly',
'Hazel English',
'Miki Fiki',
'Louis The Child',
'Demi Lovato',
'Fruit Bats',
'Mike Shinoda',
'Jess Best',
'Ricky Reed',
'Hozier',
'Fishing in Japan',
'India Shawn',
'Hope Tala',
'Bibio',
'Jackson Lundy',
'Black Pumas',
'Bishop Briggs',
'keshi',
'HNNY',
'Derek Simpson',
'88rising',
'Hether',
'Vansire',
'KASSEO',
'Paloma Faith',
'The Japanese House',
'Rook Monroe',
'Wes Reeve',
'Matt Quentin',
'vbnd',
'Cape Francis',
'NGHTMRE',
'Healy',
'Tommy Newport',
'Moi Je',
'FELIVAND',
'New West',
'Eleni Drake',
'This Is The Kit',
'Devon Gilfillian',
'French For Rabbits',
'Tash Sultana',
'Lil Nas X',
'C2C',
'Alë Jay',
'Tora',
'ayokay',
'K. Roosevelt',
'¿Téo?',
'Golden Vessel',
'Young Thug',
'BAYNK',
'Cheat Codes',
'Lexi Jayde',
'Wallows',
'Tiana Major9',
'Tourist',
'Tōth',
'Honeywhip',
'Marvin Gaye',
'Szymon',
'Busta Rhymes',
'Santana',
'Gregory Alan Isakov',
'Portugal. The Man',
'Matoma',
'Avicii',
'Disclosure',
'Darius',
'Miles Davis',
'Yahtzel',
'Mutemath',
'Kartell',
'Roy Woods',
'Tunji Ige',
'Manila Killa',
'The Dramatics',
'Injury Reserve',
'YOSIE',
'Henry Green',
'Giraffage',
'Beshken',
'Commodores',
'Seal',
'Raury',
'Major Lazer',
'Kygo',
'Night Moves',
'Seinabo Sey',
'Isaiah Rashad',
'Knox Fortune',
'Toploader',
'Garren Sean',
'BADBADNOTGOOD',
'Royal Tongues',
'XY&O',
'Foxygen',
'Jamie xx',
'CeeLo Green',
'B.o.B',
'Masego',
'Jacob Collier',
'Whethan',
'Hayden James',
'Jordan Rakei',
'MKTO',
'Jeremih',
'Floro',
'Marshmello',
'ZHU',
'Syd',
'Mr. Probz',
'Mary J. Blige',
'Dreamville',
'Meek Mill',
'Dido',
'Estelle',
'Louis Armstrong',
'Julie London',
'JID',
'Marian Hill',
'Ra Ra Riot',
'A$AP Twelvyy',
'Earl Sweatshirt',
'tobi lou',
'Russ',
'VIC MENSA',
'Snoop Dogg',
'Huncho Jack',
'Mild High Club',
'Brian Culbertson',
'The Rolling Stones',
'Catching Flies',
'Appleby',
'Social House',
'GoldLink',
'Aphex Twin',
'McClenney',
'Dream Koala',
'Hoodie Allen',
'Tiara Thomas',
'Fyfe',
'Hippie Sabotage',
'Two Another',
'Clean Bandit',
'Craft Spells',
'Verzache',
'Selena Gomez',
'The Marías',
'Choker',
'Lizzo',
'Steve Lacy',
'Kasbo',
'Hablot Brown',
'DRAMA',
'Jarryd James',
'Gnarls Barkley',
'meija',
'Girlyboi',
'Khruangbin',
'Peach Tree Rascals',
'Litany',
'THEY.',
'Loyle Carner',
'Crumb',
'Elton Aura',
'Rizzle Kicks',
'Bonobo',
'Solange',
'Two Feet',
'The Hails',
'Sjowgren',
'Galimatias',
'Kali Uchis',
'Mick Jenkins',
'Phum Viphurit',
'Kelsy Karter',
'Jalen Santoy',
'The Carters',
'Tove Styrke',
'The Notorious B.I.G.',
'Ralph Castelli',
'Ruel',
'Sinéad Harnett',
'Summer Walker',
'Danrell x Småland',
'MGMT',
'Daft Punk',
'Jason Mraz',
'Empire of the Sun',
'Local Natives',
'MELVV',
'Sampha',
'Party Pupils',
'ScHoolboy Q',
'Bob Marley & The Wailers',
'Grizzly Bear',
'Kool & The Gang',
'Sports',
'Hollow Coves']



# y = [
# 	36, 28, 26, 24, 20, 20, 19, 18, 17, 16, 16, 16, 16, 15, 15, 15, 15, 14, 14, 
# 	13, 13, 13, 13, 12, 12, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 
# 	9, 9, 9, 9, 9, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 
# 	6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
# 	5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
# 	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
# 	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
# 	3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
# 	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
# 	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
# 	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
# ]
y = [36,
28,
26,
24,
20,
20,
19,
18,
17,
16,
16,
16,
16,
15,
15,
15,
15,
14,
14,
13,
13,
13,
13,
12,
12,
11,
11,
11,
11,
11,
10,
10,
10,
10,
10,
10,
10,
10,
9,
9,
9,
9,
9,
8,
8,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1]

# def format_str(lst):
# 	a = []
# 	for artist in lst:
# 		a.append(artist)
# 	print(a)


	# return re.sub('[a-zA-Z]\' \'[a-aA-Z]', '\', \'', lst[0])
	



# print(format_str(x))
# print(x)

# a = [
# 'Kanye West',
# 'Drake',
# 'Tom Misch',
# 'Mac Miller',
# 'Kendrick Lamar',
# 'Tame Impala',
# 'BROCKHAMPTON',
# 'Lana Del Rey',
# 'John Legend',
# 'Anderson .Paak'
# ]
# b = [36,
# 28,
# 26,
# 24,
# 20,
# 20,
# 19,
# 18,
# 17,
# 16]

# # print(len(x), len(y))


# plt.bar(a, b)
# plt.title('Songs by Artist')
# plt.set_window_title('Test')
# # plt.xticks(rotation = 25)
# # plt.figure(figsize=(20,10))
# plt.xlabel('artist')
# plt.ylabel('# songs')
plt.show()